modLoader = "javafml"
loaderVersion = "[11,)"
license = "MIT"

[[mods]]
modId = "halfbright"
version = "${version}"
displayName = "Halfbright"
authors = "L3-N0X"
description = "Halfbright allows Minecraft to be brighter without looking worse"

[[mixins]]
config = "halfbright.mixins.json"
